arch: null
artifacts: []
environment:
  NIXPKGS_ALLOW_BROKEN: 1
  PORT: 8080
image: nixos/20.09
packages: []
secrets: []
shell: false
triggers: []

sources:
- https://github.com/bsima/urbit-airlock

tasks:
- build: |
    cd urbit-airlock
    nix-build
#- test: |
#    cd urbit-airlock
#    # get urbit
#    curl -O https://bootstrap.urbit.org/urbit-v0.10.8-linux64.tgz
#    tar xzf urbit-v0.10.8-linux64.tgz
#    mkdir ~/bin
#    install ./urbit-v0.10.8-linux64/urbit ~/bin
#    export PATH=~/bin:$PATH
#    # start urbit daemon
#    ./fakezod.sh
#    # run tests
#    nix-shell --command "runghc ./test.hs"
